cuda_compiler:          # [win]
  - nvcc                # [win]
cuda_compiler_version:  # [win]
  - None                # [win]
  - 10.0                # [win]
  - 10.1                # [win]
  - 10.2                # [win]
  - 11.0                # [win]
