docker_image:
  - quay.io/condaforge/linux-anvil-cos7-x86_64     # [linux64]
  - quay.io/condaforge/linux-anvil-cos7-cuda:10.1  # [linux64 and os.environ.get("BUILD_PLATFORM") == "linux-64"]
  - quay.io/condaforge/linux-anvil-cos7-cuda:10.2  # [linux64 and os.environ.get("BUILD_PLATFORM") == "linux-64"]
  - quay.io/condaforge/linux-anvil-cuda:11.0       # [linux64 and os.environ.get("BUILD_PLATFORM") == "linux-64"]

#c_compiler_version:     # [linux]
#  - 7                   # [linux64 or aarch64]
#  - 8                   # [ppc64le]
#cxx_compiler_version:   # [linux]
#  - 7                   # [linux64 or aarch64]
#  - 8                   # [ppc64le]
#
#cuda_compiler:   # [linux64 or win]
#  - nvcc         # [linux64 or win]

cuda_compiler_version:
  - None                       # [linux64]
  - 10.1                       # [linux64 or win]
  - 10.2                       # [linux64 or win]
  - 11.0                       # [linux64 or win]

cudnn:
  - undefined                  # [linux64]
  - 7                          # [linux64 or win]
  - 7                          # [linux64 or win]
  - 8                          # [linux64 or win]

cdt_name:  # [linux]
  - cos7   # [linux64]
  - cos7   # [linux64]
  - cos7   # [linux64]
  - cos7   # [linux64]

#zip_keys:
#  - - cudnn                      # [linux64 or win]
#    - cuda_compiler_version      # [linux64 or win]
#    - docker_image               # [linux64 and os.environ.get("BUILD_PLATFORM") == "linux-64"]
#    - cdt_name                   # [linux64]
