{% set version = "2.3.0.6" %}

{% if cuda_compiler_version in (None, "None", True, False) %}
{% set cuda_major = 0 %}
{% else %}
{% set cuda_major = environ.get("cuda_compiler_version", "12.0").split(".")[0] | int %}
{% endif %}

{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

{% set sha = "8903ea04daa32e25dda1b4d12cbdb475aefb2bb3f2317413b16c96fcadd8fd8b" %}  # [linux64 and (cuda_compiler_version or "").startswith("12")]
{% set sha = "fdf5b10e6d09a30dae7e2956333cdb02c580a9b61d447154b7de8127ed7fa9d8" %}  # [aarch64 and (cuda_compiler_version or "").startswith("12")]
{% set sha = "0df80ccbfc1c607290e4ee0ef6f5400deaac674f1937f4609bff9215d1c39aef" %}  # [win64 and (cuda_compiler_version or "").startswith("12")]
{% set sha = "2d2768520b2d7f76a7081ddbe64c3cf61094e3e668ea296ac943c4f8435a1441" %}  # [linux64 and (cuda_compiler_version or "").startswith("13")]
{% set sha = "380d7b2bf8f3aebbe467225345008ccb27256d60fd1dad38665f4c7d23278a76" %}  # [aarch64 and (cuda_compiler_version or "").startswith("13")]
{% set sha = "643998686714108f178d1cd395aada3dd53ac89c29bc91995c42380cc4f66cec" %}  # [win64 and (cuda_compiler_version or "").startswith("13")]

package:
  name: cutensor
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cutensor/redist/libcutensor/{{ platform }}/libcutensor-{{ platform }}-{{ version }}_cuda{{ cuda_major }}-archive.{{ extension }}
  sha256: {{ sha }}

build:
  number: 0
  skip: true  # [ppc64le or cuda_compiler_version in (undefined, "None")]
  run_exports:
    - {{ pin_subpackage('cutensor') }}
  ignore_run_exports_from:
    - {{ compiler('cuda') }}
  missing_dso_whitelist:
    - "*/libcuda.so.*"    # [linux]
    - "*/nvcuda.dll"      # [win]
  script_env:
    - cuda_major={{ cuda_major }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - arm-variant * {{ arm_variant_type }}  # [aarch64]
    - cf-nvidia-tools 1                     # [linux]
  host:
    - cuda-version {{ cuda_compiler_version }}
    - libcublas  # [(cuda_compiler_version or "").startswith("12") or (cuda_compiler_version or "").startswith("13")]
  run:
    - {{ pin_compatible("cuda-version", min_pin="x", max_pin="x") }}  # [(cuda_compiler_version or "").startswith("12") or (cuda_compiler_version or "").startswith("13")]
    - libcublas  # [(cuda_compiler_version or "").startswith("12") or (cuda_compiler_version or "").startswith("13")]
  run_constrained:
    - arm-variant * {{ arm_variant_type }}  # [aarch64]

test:
  requires:
    - git
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - {{ stdlib('c') }}
    # need the libcuda stub for import test
    - cuda-driver-dev  # [linux and ((cuda_compiler_version or "").startswith("12") or (cuda_compiler_version or "").startswith("13"))]
  files:
    - test_load_elf.c  # [linux]

about:
  home: https://developer.nvidia.com/cutensor
  license: LicenseRef-cuTENSOR-Software-License-Agreement
  license_url: https://docs.nvidia.com/cuda/cutensor/license.html
  license_file: LICENSE
  summary: Tensor Linear Algebra on NVIDIA GPUs
  description: |
    The cuTENSOR Library is a first-of-its-kind GPU-accelerated tensor linear
    algebra library providing tensor contraction, reduction and elementwise
    operations. cuTENSOR is used to accelerate applications in the areas of
    deep learning training and inference, computer vision, quantum chemistry
    and computational physics.

    License Agreements:- The packages are governed by the NVIDIA cuTENSOR
    Software License Agreement (EULA). By downloading and using the packages,
    you accept the terms and conditions of the NVIDIA cuTENSOR EULA -
    https://docs.nvidia.com/cuda/cutensor/license.html
  doc_url: https://docs.nvidia.com/cuda/cutensor/index.html
  dev_url: https://developer.nvidia.com/cutensor/downloads

extra:
  recipe-maintainers:
    - ChrisPsa
    - b-kloss
    - conda-forge/cuda
    - v0i0
    - yangcal
    - JeremyWangNVDA
    - leofang
    - jakirkham
    - mtjrider
