{% set version = "2.8.1.0" %}

{% set cuda_major = 0 %}  # [not cuda_compiler_version or cuda_compiler_version == "None"]
{% set cuda_major = (cuda_compiler_version or "12.0").split(".")[0] | int %}  # [cuda_compiler_version and cuda_compiler_version != "None"]

{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

{% set sha = "46dd5562fd7cc27fe89d07fd95ca006891680e835a6a30ea60579fb01f274690" %}  # [linux64 and (cuda_compiler_version or "").startswith("12")]
{% set sha = "d2f2237b8e9db63189de6862b47f93f4ae76954033de81bcc8f67ea80c022e94" %}  # [aarch64 and (cuda_compiler_version or "").startswith("12")]
{% set sha = "62473d196a523887804d0e9b1fdc5adf3d31b32dc3d9416e0bb5420f60f3ace6" %}  # [win64 and (cuda_compiler_version or "").startswith("12")]
{% set sha = "03051950d98911ce21d977fd7ef697b6ff963b885df8844a326e25b9d400ae7a" %}  # [linux64 and (cuda_compiler_version or "").startswith("13")]
{% set sha = "55e85748c2046e06838a125bd9b311339752afd0dfb73906e34f12397aceb475" %}  # [aarch64 and (cuda_compiler_version or "").startswith("13")]
{% set sha = "802f3b5dedc8f1d3e0eaa83e07d5ebdc0b93e8bc4a230a94a3bb124523f8b170" %}  # [win64 and (cuda_compiler_version or "").startswith("13")]

package:
  name: cutensor
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cutensor/redist/libcutensor/{{ platform }}/libcutensor-{{ platform }}-{{ version }}_cuda{{ cuda_major }}-archive.{{ extension }}
  sha256: {{ sha|default("") }}

build:
  number: 0
  skip: true  # [cuda_compiler_version in (undefined, "None")]
  run_exports:
    - {{ pin_subpackage('cutensor') }}
  ignore_run_exports_from:
    - {{ compiler('cuda') }}
  missing_dso_whitelist:
    - "*/libcuda.so.*"    # [linux]
    - "*/nvcuda.dll"      # [win]
  script_env:
    - cuda_major={{ cuda_major }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - arm-variant * {{ arm_variant_type }}  # [aarch64]
    - cf-nvidia-tools 1                     # [linux]
  host:
    - cuda-version {{ cuda_compiler_version }}
    - libcublas
    - nccl  # [linux]
  run:
    - {{ pin_compatible("cuda-version", min_pin="x", max_pin="x") }}
    - libcublas
    - nccl  # [linux]
  run_constrained:
    - arm-variant * {{ arm_variant_type }}  # [aarch64]

test:
  requires:
    - git
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - {{ stdlib('c') }}
    # need the libcuda stub for import test
    - cuda-driver-dev  # [linux]
    # NVIDIA's cuTENSORMp sample includes cuda_profiler_api.h
    - cuda-profiler-api  # [linux]
    # NVIDIA's cuTENSORMp sample uses MPI to initialize the NCCL communicator
    - openmpi  # [linux]
  files:
    - test_load_elf.c  # [linux]

about:
  home: https://developer.nvidia.com/cutensor
  license: LicenseRef-cuTENSOR-Software-License-Agreement
  license_url: https://docs.nvidia.com/cuda/cutensor/license.html
  license_file: LICENSE
  summary: Tensor Linear Algebra on NVIDIA GPUs
  description: |
    The cuTENSOR Library is a first-of-its-kind GPU-accelerated tensor linear
    algebra library providing tensor contraction, reduction and elementwise
    operations. On Linux, the package also provides cuTENSORMp for distributed
    tensor contractions across multiple processes. cuTENSOR is used to
    accelerate applications in the areas of deep learning training and
    inference, computer vision, quantum chemistry and computational physics.

    License Agreements:- The packages are governed by the NVIDIA cuTENSOR
    Software License Agreement (EULA). By downloading and using the packages,
    you accept the terms and conditions of the NVIDIA cuTENSOR EULA -
    https://docs.nvidia.com/cuda/cutensor/license.html
  doc_url: https://docs.nvidia.com/cuda/cutensor/index.html
  dev_url: https://developer.nvidia.com/cutensor/downloads

extra:
  recipe-maintainers:
    - ChrisPsa
    - b-kloss
    - conda-forge/cuda
    - v0i0
    - yangcal
    - JeremyWangNVDA
    - leofang
    - jakirkham
    - mtjrider
