build_platform:
  linux_aarch64: linux_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
workflow_settings:
  build_workspace_dir:
    - provider: azure
      platform: win_64
      value: C:\bld\
  free_disk_space:
    - provider: azure
      value: quick
  tools_install_dir:
    - provider: azure
      platform: win_64
      value: C:\Miniforge
